version: '2'
services:
    cadastroeverycare-app:
        image: cadastroeverycare
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cadastroeverycare-postgresql:5432/CadastroEverycare
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cadastroeverycare-postgresql:
        extends:
            file: postgresql.yml
            service: cadastroeverycare-postgresql
